### PR TITLE
Prefer git submodule to embedded sblgnt copy

### PR DESCRIPTION
**Pull request by lucafavatella**
## Introduction

When considering to use the py-sblgnt python package at https://pypi.python.org/pypi/py-sblgnt/0.4 two things are unclear to me wrt guarantee that the embedded sblgnt copy is in line with morphgnt/sblgnt:
- (1) Traceability of how the py-sblgnt-0.4.tar.gz artefact uploaded to https://pypi.python.org/pypi/py-sblgnt were built;
- (2) Traceability of the sblgnt copy embedded in py-sblgnt repo against morphgnt/sblgnt commit/tag.

Both (1) and (2) are verifiable manually, fetching copy of the artefacts on the filesystem and running `diff -r` or similar, but that seems cumbersome. This PR proposes a change (hopefully an improvement) towards (2); (1) is (mostly) out of scope for this PR.
## Proposal

I opened this PR as a constructive way for starting a discussion on preferred improvement on traceability of the embedded sblgnt copy that ends up in the py-sblgnt package on pypi.python.org. I dislike git submodules so I totally understand if this PR be closed straight away without merging.

I guess at the moment the py-sblgnt is built locally then uploaded to pypi.python.org with admin rights? (I am not familiar with python packages.)

My full proposal is:
- Add .travis.yml to py-sblgnt repo that, when tag is taken in py-sblgnt, run job building package and uploading artefact (tar.gz) to github [ref](https://docs.travis-ci.com/user/deployment/releases/);
- Remove copy of sblgnt embedded in py-sblgnt, and replace that with either (1) git submodule to **specific commit** (e.g. as done in this PR) or (2) one line file including commit of morphgnt/sblgnt repo;
- (Optional, partially out of scope) In morphgnt/sblgnt, when taking a tag from master take also a "sibling" tag from tisch-merge branch (e.g. tag 6.07 from master and tag 6.07-tisch-merge from tics-merge branch).

### CODE REVIEW

**Comment by alerque** [comment]
I'm not sure this makes sense. The whole point of this repo is to be a pip-installable target that has the data bundled with the library to read it. Would pip know to download the data if it was offloaded to a submodule rather than inlined? Or is pip not even reading the repo and only downloading pre-generated releases? In the case of the latter, why even have this repr? Why not just have a Travis config on the library repo that builds a pip-ready version with data and posts it to the relevant release tag?

**Comment by lucafavatella** [comment]
@alerque Thanks for your feedback, very useful.
- I had not tested pip install from git repo - I tested now and it looks working so gitmodule for pip looks ok. Please find evidence below;
- I guess this repo is separate from the sblgnt repo in order not to pollute the latter with files like the small Python API module(**init**.py), metadata (setup.py), README for API, travis dot file if any;
- I guess that had the sblgnt repo had a travis file it would not be py-sblgnt related one but rather one checking invariants on the morphological database e.g. all of the morphological analysis code are in a known list).

BTW I am an expert in neither pip or greek/morphgnt so please apologise if I am missing the point in anything major in your comment.

## Pip and submodule - evidence

```
$ pip -V
pip 7.1.2 from /.../homebrew/lib/python2.7/site-packages (python 2.7)

$ pip list | grep sbl
$ ls -a .
.                       ..                      requirements.txt
$ cat requirements.txt
-e git+https://github.com/lucafavatella/py-sblgnt/@74f7b274fb2e33cd5fc7d928ff76c3f22880a745#egg=py-sblgnt-sblgnt-as-git-submodule

$ pip install -r requirements.txt
Obtaining py-sblgnt-sblgnt-as-git-submodule from git+https://github.com/lucafavatella/py-sblgnt/@74f7b274fb2e33cd5fc7d928ff76c3f22880a745#egg=py-sblgnt-sblgnt-as-git-submodule (from
 -r requirements.txt (line 1))
  Cloning https://github.com/lucafavatella/py-sblgnt/ (to 74f7b274fb2e33cd5fc7d928ff76c3f22880a745) to ./src/py-sblgnt-sblgnt-as-git-submodule
  Could not find a tag or branch '74f7b274fb2e33cd5fc7d928ff76c3f22880a745', assuming commit.
Installing collected packages: py-sblgnt-sblgnt-as-git-submodule
  Running setup.py develop for py-sblgnt-sblgnt-as-git-submodule
Successfully installed py-sblgnt-sblgnt-as-git-submodule

$ ls -a .
.                       ..                      requirements.txt        src
$ ls -a src/
.                                       ..                                      pip-delete-this-directory.txt           py-sblgnt-sblgnt-as-git-submodule
$ pip list | grep sbl
py-sblgnt (0.4, /.../py-sblgnt/src/py-sblgnt-sblgnt-as-git-submodule)

$ echo "import pysblgnt
print pysblgnt.morphgnt_rows(1).next()
" | python
{'word': '\xce\x92\xce\xaf\xce\xb2\xce\xbb\xce\xbf\xcf\x82', 'text': '\xce\x92\xce\xaf\xce\xb2\xce\xbb\xce\xbf\xcf\x82', 'ccat-parse': '----NSF-', 'ccat-pos': 'N-', 'lemma': '\xce\$b2\xce\xaf\xce\xb2\xce\xbb\xce\xbf\xcf\x82', 'bcv': '010101', 'robinson': 'N-NSF', 'norm': '\xce\xb2\xce\xaf\xce\xb2\xce\xbb\xce\xbf\xcf\x82'}
```

**Comment by jtauber** [comment]
regarding "I guess that had the sblgnt repo had a travis file it would not be py-sblgnt related one but rather one checking invariants on the morphological database"

Yes. Any travis checks on sblgnt would just check integrity of data. Travis checks on py-sblgnt would test the python API.

**Comment by jtauber** [comment]
I too am not a fan of git submodules but I do want to remove the redundancy of manually copying over the sblgnt repo into this one to do a release. @alerque makes a good point about making sure this works both for PyPI AND for people installing directly from git (although tbh, I could live with the latter not working if the former does)

**Comment by jtauber** [comment]
regarding "I guess this repo is separate from the sblgnt repo in order not to pollute the latter..." the goal is to keep sblgnt programming language independent for end-users (although it may have code in it to verify and clean up the data)

**Comment by lucafavatella** [comment]
@jtauber Do I understand correctly that the term PyPI in the statement "... making sure this works both for PyPI ..." refer to https://pypi.python.org/pypi/py-sblgnt/ ? How can I help testing that?

**Comment by jtauber** [comment]
@lucafavatella I don't think you can test PyPI uploading. But I can try it and if it doesn't work, just do another release :-)

**Comment by jtauber** [comment]
I'm actually more worried about the git case than the PyPI case as I can always make sure the submodule is updated before doing a PyPI release.

**Comment by jtauber** [comment]
I doubt a pip install from git will expand the git submodules

**Comment by lucafavatella** [comment]
I believe I tested pip install from git in my comment above. Did I miss
anything?

**Comment by jtauber** [comment]
@lucafavatella sorry yes your comment above does suggest pip installing from git actually honors submodules (which amazes me). Perhaps I should just release 0.5.1 with submodules and if something doesn't work, I can just release 0.5.2 that reverts.

**Comment by lucafavatella** [comment]
Thinking more about pip install from git, probably pip delegates the git
operations to the native git in the PATH hence, depending on different
support and defaults wrt submodules in that git version, different versions
of git would produce different outcomes when pip install-ing from git. E.g.
if user has old version of git installed and performs pip install from git,
maybe user may get unexpected result e.g. partial checkout. I assume pip
skip user customizations of git options defaults.
(All of the above is just speculation - not sure it may even happen e.g.
not sure how much git behaviour changed over time wrt submodules. And I
will have limited internet access for a few days.)

I am not sure whether there is a pip community best practice on git
submodules.

**Comment by jtauber** [comment]
And the more I think about this I wonder how much we're actually saving using submodules besides disk space.

I mean what I do now is trivial:

cp ../sblgnt/*-morphgnt.txt pysblgnt/sblgnt/
[update setup.py version]
python setup.py sdist upload

**Comment by lucafavatella** [comment]
I appreciate your concerns. If unsure feel free to close without merge, and
thanks for considering this proposal.

**Comment by jtauber** [comment]
Going to close this but I wonder if it's worth adding some CI that tests if the sblgnt copy is up-to-date. That way if I go to tag a new release, it will at least fail if I've forgotten to update the data.

**Pull request closed without merging**
